[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
extra_scripts = pre:tools/generate_sprites.py
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
