[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
extra_scripts = pre:tools/generate_sprites.py
monitor_speed = 115200
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit ST7735 and ST7789 Library
build_src_filter =
  +<*>
  -<st7789_test.cpp>
  -<gpio_test.cpp>
  -<raw_st7789_test.cpp>
  -<hardware_st7789_test.cpp>

[env:st7789-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
build_src_filter =
  -<*>
  +<st7789_test.cpp>

[env:gpio-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  -<*>
  +<gpio_test.cpp>

[env:raw-st7789-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  -<*>
  +<raw_st7789_test.cpp>

[env:hardware-st7789-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  -<*>
  +<hardware_st7789_test.cpp>
