#pragma once

#include "generated_tft_assets.h"
#include "walk_cycle.h"

// Stable species identifiers; independent of the sorted Flash catalog IDs.
enum class MascotId : uint8_t {
  DRAGON = 0,
  BLUE_CAT = 1,
  RED_DOG = 2,
  GREEN_MOUSE = 3,
  YELLOW_BIRD = 4,
  PURPLE_SALAMANDER = 5,
  COUNT = 6,
};

struct MascotWalk {
  const char* label;
  TftAssetId left[WalkCycle::kFrames];
  TftAssetId right[WalkCycle::kFrames];
};

inline const MascotWalk& mascotWalk(MascotId mascot) {
  static const MascotWalk walks[] = {
    { "Dragon",
      { TftAssetId::DRAGON_RIGGED_WALK_LEFT_01, TftAssetId::DRAGON_RIGGED_WALK_LEFT_02, TftAssetId::DRAGON_RIGGED_WALK_LEFT_03, TftAssetId::DRAGON_RIGGED_WALK_LEFT_04, TftAssetId::DRAGON_RIGGED_WALK_LEFT_05, TftAssetId::DRAGON_RIGGED_WALK_LEFT_06, TftAssetId::DRAGON_RIGGED_WALK_LEFT_07, TftAssetId::DRAGON_RIGGED_WALK_LEFT_08 },
      { TftAssetId::DRAGON_RIGGED_WALK_RIGHT_01, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_02, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_03, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_04, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_05, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_06, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_07, TftAssetId::DRAGON_RIGGED_WALK_RIGHT_08 } },
    { "Chat",
      { TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_01, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_02, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_03, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_04, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_05, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_06, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_07, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_LEFT_08 },
      { TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_01, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_02, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_03, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_04, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_05, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_06, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_07, TftAssetId::BLUE_CAT_RIGGED_FEET_V4_WALK_RIGHT_08 } },
    { "Chien",
      { TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_01, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_02, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_03, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_04, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_05, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_06, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_07, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_LEFT_08 },
      { TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_01, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_02, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_03, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_04, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_05, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_06, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_07, TftAssetId::RED_DOG_RIGGED_FEET_V4_WALK_RIGHT_08 } },
    { "Souris",
      { TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_01, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_02, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_03, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_04, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_05, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_06, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_07, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_LEFT_08 },
      { TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_01, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_02, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_03, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_04, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_05, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_06, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_07, TftAssetId::GREEN_MOUSE_RIGGED_FEET_V4_WALK_RIGHT_08 } },
    { "Oiseau",
      { TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_01, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_02, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_03, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_04, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_05, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_06, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_07, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_LEFT_08 },
      { TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_01, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_02, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_03, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_04, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_05, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_06, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_07, TftAssetId::YELLOW_BIRD_RIGGED_FEET_V4_WALK_RIGHT_08 } },
    { "Salamandre",
      { TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_01, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_02, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_03, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_04, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_05, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_06, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_07, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_LEFT_08 },
      { TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_01, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_02, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_03, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_04, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_05, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_06, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_07, TftAssetId::PURPLE_SALAMANDER_RIGGED_FEET_V4_WALK_RIGHT_08 } },
  };
  static_assert(sizeof(walks) / sizeof(walks[0]) == static_cast<uint8_t>(MascotId::COUNT),
                "Every species requires a complete approved walk");
  const uint8_t index = static_cast<uint8_t>(mascot);
  return walks[index < static_cast<uint8_t>(MascotId::COUNT) ? index : 0];
}

inline TftAssetId mascotWalkFrame(MascotId mascot, bool right, uint8_t phase) {
  const MascotWalk& walk = mascotWalk(mascot);
  return (right ? walk.right : walk.left)[phase % WalkCycle::kFrames];
}
