"""Convert 1-bit BMP sprite sources into an SSD1306-compatible C++ header."""

from __future__ import annotations

import re
import struct
from pathlib import Path


try:
    Import("env")
except NameError:
    BUILD_ENV = None
    PROJECT_ROOT = Path(__file__).resolve().parents[1]
else:
    BUILD_ENV = env
    PROJECT_ROOT = Path(BUILD_ENV["PROJECT_DIR"])

ASSETS_DIR = PROJECT_ROOT / "assets" / "sprites"
OUTPUT_PATH = PROJECT_ROOT / "include" / "generated_sprites.h"


def sprite_name(path: Path) -> str:
    name = re.sub(r"[^a-z0-9_]", "_", path.stem.lower())
    if not name.startswith("dragon_"):
        raise ValueError(f"{path.name}: sprite names must start with 'dragon_'")
    return name


def read_bmp(path: Path) -> tuple[int, int, list[bool]]:
    data = path.read_bytes()
    if len(data) < 62 or data[:2] != b"BM":
        raise ValueError(f"{path.name}: expected a BMP file")

    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    dib_size = struct.unpack_from("<I", data, 14)[0]
    width, height = struct.unpack_from("<ii", data, 18)
    planes, bits_per_pixel = struct.unpack_from("<HH", data, 26)
    compression = struct.unpack_from("<I", data, 30)[0]
    if dib_size < 40 or planes != 1 or bits_per_pixel != 1 or compression != 0:
        raise ValueError(f"{path.name}: expected an uncompressed 1-bit BMP")
    if width <= 0 or height == 0 or width > 128 or abs(height) > 48:
        raise ValueError(f"{path.name}: dimensions must fit within 128x48 px")

    palette_offset = 14 + dib_size
    if pixel_offset < palette_offset + 8:
        raise ValueError(f"{path.name}: missing two-color palette")
    palette = [data[palette_offset + index * 4 : palette_offset + index * 4 + 3]
               for index in range(2)]
    luminance = [blue * 114 + green * 587 + red * 299 >= 127_500
                 for blue, green, red in palette]

    absolute_height = abs(height)
    source_row_bytes = ((width + 31) // 32) * 4
    if pixel_offset + source_row_bytes * absolute_height > len(data):
        raise ValueError(f"{path.name}: pixel data is incomplete")

    pixels: list[bool] = []
    for y in range(absolute_height):
        source_y = absolute_height - 1 - y if height > 0 else y
        row_start = pixel_offset + source_y * source_row_bytes
        for x in range(width):
            color_index = (data[row_start + x // 8] >> (7 - x % 8)) & 1
            pixels.append(luminance[color_index])
    return width, absolute_height, pixels


def bitmap_bytes(width: int, height: int, pixels: list[bool]) -> list[int]:
    row_bytes = (width + 7) // 8
    output = [0] * (row_bytes * height)
    for y in range(height):
        for x in range(width):
            if pixels[y * width + x]:
                output[y * row_bytes + x // 8] |= 0x80 >> (x % 8)
    return output


def format_bytes(values: list[int]) -> str:
    lines = []
    for start in range(0, len(values), 12):
        chunk = ", ".join(f"0x{value:02X}" for value in values[start : start + 12])
        lines.append(f"  {chunk},")
    return "\n".join(lines)


def generate() -> None:
    sources = sorted(ASSETS_DIR.glob("*.bmp"))
    if not sources:
        raise ValueError(f"No BMP sprites found in {ASSETS_DIR}")

    sprites = [(sprite_name(path), *read_bmp(path)) for path in sources]
    width, height = sprites[0][1:3]
    for name, sprite_width, sprite_height, _ in sprites:
        if (sprite_width, sprite_height) != (width, height):
            raise ValueError(
                f"{name}: all sprites must use the same dimensions "
                f"({width}x{height} expected)")

    header = [
        "// Generated by tools/generate_sprites.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        f"constexpr uint8_t DRAGON_SPRITE_WIDTH = {width};",
        f"constexpr uint8_t DRAGON_SPRITE_HEIGHT = {height};",
        "",
    ]
    for name, _, _, pixels in sprites:
        header.append(f"const unsigned char {name}[] PROGMEM = {{")
        header.append(format_bytes(bitmap_bytes(width, height, pixels)))
        header.append("};")
        header.append("")

    OUTPUT_PATH.write_text("\n".join(header), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(PROJECT_ROOT)} from {len(sprites)} BMP sprites")


if BUILD_ENV is not None or __name__ == "__main__":
    generate()
